name: 'ecommerce_dbt'
version: '1.0'
config-version: 2

profile: 'ecommerce_dbt'   # <- Must match the name in profiles.yml

model-paths: ["models"]

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
